import type { Product, Category } from './types';

export const categories: Category[] = [
  { id: 'cat-1', name: 'Men\'s Clothing', slug: 'mens-clothing', imageId: 'mens-category' },
  { id: 'cat-2', name: 'Women\'s Clothing', slug: 'womens-clothing', imageId: 'womens-category' },
  { id: 'cat-3', name: 'Accessories', slug: 'accessories', imageId: 'accessories-category' },
  { id: 'cat-5', name: 'Shoes', slug: 'shoes', imageId: 'shoes-category' },
  { id: 'cat-4', name: 'Winter Wear', slug: 'winter-clothing', imageId: 'winter-category' },
];

export const products: Product[] = [
  // Winter Wear - Men
  {
    id: 'prod-winter-1',
    name: 'Manteau Long en Laine Hugo Boss',
    slug: 'manteau-long-laine-hugo-boss',
    price: 799.00,
    description: 'Un manteau long classique en laine vierge, offrant chaleur et une silhouette impeccablement élégante par Hugo Boss.',
    category: 'winter-clothing',
    images: ['manteau-long-laine-hugo-boss'],
    reviews: [],
  },
  {
    id: 'prod-winter-2',
    name: 'Doudoune Matelassée Moncler',
    slug: 'doudoune-matelassee-moncler',
    price: 1250.00,
    description: 'La doudoune emblématique de Moncler, alliant performance technique et style alpin pour une protection optimale contre le froid.',
    category: 'winter-clothing',
    images: ['doudoune-matelassee-moncler'],
    reviews: [],
  },
  {
    id: 'prod-winter-3',
    name: 'Parka Arctic Canada Goose',
    slug: 'parka-arctic-canada-goose',
    price: 1150.00,
    description: 'Conçue pour les climats les plus extrêmes, la parka Arctic de Canada Goose est le summum de la chaleur et de la durabilité.',
    category: 'winter-clothing',
    images: ['parka-arctic-canada-goose'],
    reviews: [],
  },
  {
    id: 'prod-winter-4',
    name: 'Manteau Cachemire Loro Piana Homme',
    slug: 'manteau-cachemire-loro-piana-homme',
    price: 4500.00,
    description: 'Le luxe à l\'état pur. Ce manteau Loro Piana en cachemire double face est d\'une douceur et d\'une chaleur incomparables.',
    category: 'mens-clothing',
    images: ['manteau-cachemire-loro-piana-homme'],
    reviews: [],
  },
  {
    id: 'prod-winter-5',
    name: 'Blouson Shearling Saint Laurent',
    slug: 'blouson-shearling-saint-laurent',
    price: 4800.00,
    description: 'Un blouson aviateur audacieux en peau de mouton retournée par Saint Laurent, pour un style rock et luxueux.',
    category: 'mens-clothing',
    images: ['blouson-shearling-saint-laurent'],
    reviews: [],
  },
  {
    id: 'prod-winter-6',
    name: 'Pull Col Roulé Laine Mérinos Paul Smith',
    slug: 'pull-col-roule-laine-merinos-paul-smith',
    price: 350.00,
    description: 'Un essentiel de l\'hiver, ce pull à col roulé en fine laine mérinos de Paul Smith est aussi doux que polyvalent.',
    category: 'mens-clothing',
    images: ['pull-col-roule-laine-merinos-paul-smith'],
    reviews: [],
  },
  {
    id: 'prod-winter-7',
    name: 'Surchemise Doublée Acne Studios Homme',
    slug: 'surchemise-doublee-acne-studios-homme',
    price: 420.00,
    description: 'La surchemise en flanelle de laine doublée par Acne Studios, parfaite pour une superposition de mi-saison avec une touche scandinave.',
    category: 'mens-clothing',
    images: ['surchemise-doublee-acne-studios-homme'],
    reviews: [],
  },
  {
    id: 'prod-winter-8',
    name: 'Doudoune Sans Manche Polo Ralph Lauren',
    slug: 'doudoune-sans-manche-polo-ralph-lauren',
    price: 250.00,
    description: 'Légère et pratique, cette doudoune sans manche est un classique de Polo Ralph Lauren, idéale sur un pull ou sous un manteau.',
    category: 'winter-clothing',
    images: ['doudoune-sans-manche-polo-ralph-lauren'],
    reviews: [],
  },
  {
    id: 'prod-winter-9',
    name: 'Manteau Trench Double Burberry',
    slug: 'manteau-trench-double-burberry',
    price: 1990.00,
    description: 'L\'iconique trench-coat Burberry. Une pièce intemporelle et résistante aux intempéries, symbole d\'élégance britannique.',
    category: 'winter-clothing',
    images: ['manteau-trench-double-burberry'],
    reviews: [],
  },
  {
    id: 'prod-winter-10',
    name: 'Pull Torsadé Épais Dior Homme',
    slug: 'pull-torsade-epais-dior-homme',
    price: 1100.00,
    description: 'Un pull richement texturé en laine et cachemire, orné de torsades classiques. Une pièce maîtresse signée Dior.',
    category: 'mens-clothing',
    images: ['pull-torsade-epais-dior-homme'],
    reviews: [],
  },
  {
    id: 'prod-winter-11',
    name: 'Veste Technique Imperméable TNF Black Series',
    slug: 'veste-technique-impermeable-tnf-black-series',
    price: 650.00,
    description: 'Issue de la ligne haut de gamme de The North Face, cette veste combine design futuriste et protection maximale contre les éléments.',
    category: 'winter-clothing',
    images: ['veste-technique-impermeable-tnf-black-series'],
    reviews: [],
  },
  // Winter Wear - Women
  {
    id: 'prod-winter-12',
    name: 'Robe Midi en Soie Gucci',
    slug: 'robe-midi-en-soie-gucci',
    price: 2500.00,
    description: 'Une robe midi en crêpe de soie signée Gucci, ornée d\'un imprimé audacieux pour une élégance maximale.',
    category: 'womens-clothing',
    images: ['robe-midi-en-soie-gucci'],
    reviews: [],
  },
  {
    id: 'prod-winter-13',
    name: 'Blazer Croisé Balmain',
    slug: 'blazer-croise-balmain',
    price: 2200.00,
    description: 'L\'emblématique blazer croisé Balmain avec ses boutons dorés, une pièce forte qui structure la silhouette avec audace.',
    category: 'womens-clothing',
    images: ['blazer-croise-balmain'],
    reviews: [],
  },
  {
    id: 'prod-winter-14',
    name: 'Pull Col Roulé Cachemire Loro Piana Femme',
    slug: 'pull-col-roule-cachemire-loro-piana-femme',
    price: 1800.00,
    description: 'La quintessence du luxe et du confort. Ce pull à col roulé Loro Piana en pur cachemire est une seconde peau.',
    category: 'womens-clothing',
    images: ['pull-col-roule-cachemire-loro-piana-femme'],
    reviews: [],
  },
  {
    id: 'prod-winter-15',
    name: 'Pantalon Large en Laine Max Mara',
    slug: 'pantalon-large-en-laine-max-mara',
    price: 650.00,
    description: 'Un pantalon large à la coupe parfaite, confectionné en laine fluide par Max Mara pour une allure chic et décontractée.',
    category: 'womens-clothing',
    images: ['pantalon-large-en-laine-max-mara'],
    reviews: [],
  },
  {
    id: 'prod-winter-16',
    name: 'Jean Slim Premium Diesel',
    slug: 'jean-slim-premium-diesel',
    price: 280.00,
    description: 'Un jean slim à la coupe parfaite et au délavage subtil, conçu dans un denim de haute qualité par Diesel.',
    category: 'womens-clothing',
    images: ['jean-slim-premium-diesel'],
    reviews: [],
  },
  {
    id: 'prod-winter-17',
    name: 'Chemisier en Soie Imprimée Saint Laurent',
    slug: 'chemisier-en-soie-imprimee-saint-laurent',
    price: 1350.00,
    description: 'Élégance et modernité se rencontrent dans ce chemisier en soie fluide orné d\'un imprimé exclusif Saint Laurent.',
    category: 'womens-clothing',
    images: ['chemisier-en-soie-imprimee-saint-laurent'],
    reviews: [],
  },
  {
    id: 'prod-winter-18',
    name: 'Robe Courte en Laine Prada',
    slug: 'robe-courte-en-laine-prada',
    price: 1700.00,
    description: 'Une robe courte à la silhouette structurée en laine fine, emblématique du minimalisme chic de Prada.',
    category: 'womens-clothing',
    images: ['robe-courte-en-laine-prada'],
    reviews: [],
  },
  {
    id: 'prod-winter-19',
    name: 'Manteau Long en Cachemire Max Mara',
    slug: 'manteau-long-en-cachemire-max-mara',
    price: 4800.00,
    description: 'Le manteau iconique \'Manuela\' de Max Mara en pur cachemire, une pièce intemporelle d\'une élégance absolue.',
    category: 'womens-clothing',
    images: ['manteau-long-en-cachemire-max-mara'],
    reviews: [],
  },
  {
    id: 'prod-winter-20',
    name: 'Veste Courte Matelassée Moncler',
    slug: 'veste-courte-matelassee-moncler',
    price: 990.00,
    description: 'Une veste courte et matelassée qui combine la performance Moncler avec une silhouette féminine et moderne.',
    category: 'womens-clothing',
    images: ['veste-courte-matelassee-moncler'],
    reviews: [],
  },
  {
    id: 'prod-winter-21',
    name: 'Pull Oversize Torsadé Chloé',
    slug: 'pull-oversize-torsade-chloe',
    price: 1200.00,
    description: 'Un pull oversize en maille torsadée épaisse, incarnant le romantisme bohème de la maison Chloé.',
    category: 'womens-clothing',
    images: ['pull-oversize-torsade-chloe'],
    reviews: [],
  },
  {
    id: 'prod-winter-22',
    name: 'Jupe Crayon en Laine Hugo Boss',
    slug: 'jupe-crayon-en-laine-hugo-boss',
    price: 350.00,
    description: 'Une jupe crayon parfaitement coupée en laine stretch par Hugo Boss, essentielle pour une garde-robe professionnelle.',
    category: 'womens-clothing',
    images: ['jupe-crayon-en-laine-hugo-boss'],
    reviews: [],
  },
  {
    id: 'prod-winter-23',
    name: 'Robe Longue Plissée Valentino',
    slug: 'robe-longue-plissee-valentino',
    price: 3900.00,
    description: 'Une création spectaculaire signée Valentino, cette robe longue en tissu plissé flotte à chaque mouvement.',
    category: 'womens-clothing',
    images: ['robe-longue-plissee-valentino'],
    reviews: [],
  },
  {
    id: 'prod-winter-24',
    name: 'Chemise en Coton Premium Burberry',
    slug: 'chemise-en-coton-premium-burberry',
    price: 450.00,
    description: 'Une chemise blanche impeccable en coton premium, rehaussée de détails subtils comme le tartan iconique à l\'intérieur du col.',
    category: 'womens-clothing',
    images: ['chemise-en-coton-premium-burberry'],
    reviews: [],
  },
  {
    id: 'prod-winter-25',
    name: 'Robe Portefeuille en Soie Diane von Furstenberg',
    slug: 'robe-portefeuille-en-soie-diane-von-furstenberg',
    price: 550.00,
    description: 'L\'iconique robe portefeuille DVF en jersey de soie, une pièce qui flatte toutes les silhouettes avec une élégance intemporelle.',
    category: 'womens-clothing',
    images: ['robe-portefeuille-en-soie-diane-von-furstenberg'],
    reviews: [],
  },
  {
    id: 'prod-winter-26',
    name: 'Pantalon Tailleur Dior Femme',
    slug: 'pantalon-tailleur-dior-femme',
    price: 1200.00,
    description: 'Un pantalon tailleur à la coupe impeccable, reflétant le savoir-faire et l\'élégance de la maison Dior.',
    category: 'womens-clothing',
    images: ['pantalon-tailleur-dior-femme'],
    reviews: [],
  },
  {
    id: 'prod-winter-27',
    name: 'Pull Col Bateau Ralph Lauren',
    slug: 'pull-col-bateau-ralph-lauren',
    price: 320.00,
    description: 'Un pull classique à col bateau en maille fine, une pièce polyvalente et chic signée Ralph Lauren.',
    category: 'womens-clothing',
    images: ['pull-col-bateau-ralph-lauren'],
    reviews: [],
  },
  {
    id: 'prod-winter-28',
    name: 'Cardigan Long en Cachemire Brunello Cucinelli',
    slug: 'cardigan-long-en-cachemire-brunello-cucinelli',
    price: 2900.00,
    description: 'La quintessence du luxe décontracté. Ce cardigan long et enveloppant est tricoté dans le plus fin des cachemires.',
    category: 'womens-clothing',
    images: ['cardigan-long-en-cachemire-brunello-cucinelli'],
    reviews: [],
  },
  {
    id: 'prod-winter-29',
    name: 'Robe Asymétrique Givenchy',
    slug: 'robe-asymetrique-givenchy',
    price: 2100.00,
    description: 'Une robe noire à la coupe asymétrique audacieuse, emblématique du style architectural et moderne de Givenchy.',
    category: 'womens-clothing',
    images: ['robe-asymetrique-givenchy'],
    reviews: [],
  },
  {
    id: 'prod-winter-30',
    name: 'Blouse Satinée Stella McCartney',
    slug: 'blouse-satinee-stella-mccartney',
    price: 650.00,
    description: 'Une blouse fluide et élégante en satin de soie durable, parfaite pour un look sophistiqué et conscient.',
    category: 'womens-clothing',
    images: ['blouse-satinee-stella-mccartney'],
    reviews: [],
  },
  {
    id: 'prod-winter-31',
    name: 'Combinaison-Pantalon Balenciaga',
    slug: 'combinaison-pantalon-balenciaga',
    price: 2400.00,
    description: 'Une pièce forte au design avant-gardiste. Cette combinaison-pantalon Balenciaga sculpte une silhouette moderne et puissante.',
    category: 'womens-clothing',
    images: ['combinaison-pantalon-balenciaga'],
    reviews: [],
  },
  {
    id: 'prod-winter-32',
    name: 'Manteau Oversize Acne Studios',
    slug: 'manteau-oversize-acne-studios',
    price: 1100.00,
    description: 'Un manteau oversize en laine double face, signature du style cool et minimaliste d\'Acne Studios.',
    category: 'womens-clothing',
    images: ['manteau-oversize-acne-studios'],
    reviews: [],
  },
  {
    id: 'prod-winter-33',
    name: 'Robe-Pull en Cachemire Max Mara',
    slug: 'robe-pull-en-cachemire-max-mara',
    price: 1300.00,
    description: 'Alliant confort et élégance, cette robe-pull en pur cachemire est une pièce luxueuse et cosy pour l\'hiver.',
    category: 'womens-clothing',
    images: ['robe-pull-en-cachemire-max-mara'],
    reviews: [],
  },
  {
    id: 'prod-winter-34',
    name: 'Pantalon en Cuir Saint Laurent',
    slug: 'pantalon-en-cuir-saint-laurent',
    price: 2800.00,
    description: 'Un pantalon skinny en cuir d\'agneau stretch, pièce iconique du vestiaire rock et chic de Saint Laurent.',
    category: 'womens-clothing',
    images: ['pantalon-en-cuir-saint-laurent'],
    reviews: [],
  },
  {
    id: 'prod-winter-35',
    name: 'Jupe Plissée Midi Valentino',
    slug: 'jupe-plissee-midi-valentino',
    price: 1800.00,
    description: 'Une jupe midi au plissé soleil délicat, qui bouge avec grâce à chaque pas. Une pièce emblématique de Valentino.',
    category: 'womens-clothing',
    images: ['jupe-plissee-midi-valentino'],
    reviews: [],
  },
  {
    id: 'prod-winter-36',
    name: 'T-shirt Brodé Logo Gucci',
    slug: 't-shirt-brode-logo-gucci',
    price: 550.00,
    description: 'Un t-shirt en coton de haute qualité, rehaussé du logo Gucci brodé pour une touche de luxe décontracté.',
    category: 'womens-clothing',
    images: ['t-shirt-brode-logo-gucci'],
    reviews: [],
  },
  {
    id: 'prod-winter-37',
    name: 'Pull Col Bateau Manches Ballon Chloé',
    slug: 'pull-col-bateau-manches-ballon-chloe',
    price: 950.00,
    description: 'Un pull romantique avec un col bateau élégant et des manches ballon volumineuses, typique du style Chloé.',
    category: 'womens-clothing',
    images: ['pull-col-bateau-manches-ballon-chloe'],
    reviews: [],
  },
  {
    id: 'prod-winter-38',
    name: 'Robe-Chemise Oversize Balenciaga',
    slug: 'robe-chemise-oversize-balenciaga',
    price: 1250.00,
    description: 'Une robe-chemise à la coupe oversize audacieuse, pour un look déconstruit et conceptuel signé Balenciaga.',
    category: 'womens-clothing',
    images: ['robe-chemise-oversize-balenciaga'],
    reviews: [],
  },
  {
    id: 'prod-winter-39',
    name: 'Pantalon Palazzo en Laine Max Mara',
    slug: 'pantalon-palazzo-en-laine-max-mara',
    price: 750.00,
    description: 'Un pantalon palazzo ample et fluide en laine vierge, qui allonge la silhouette avec une élégance spectaculaire.',
    category: 'womens-clothing',
    images: ['pantalon-palazzo-en-laine-max-mara'],
    reviews: [],
  },
  {
    id: 'prod-winter-40',
    name: 'Blazer Satin Saint Laurent',
    slug: 'blazer-satin-saint-laurent',
    price: 2600.00,
    description: 'Inspiré du smoking, ce blazer en satin duchesse offre une allure nocturne et ultra-sophistiquée.',
    category: 'womens-clothing',
    images: ['blazer-satin-saint-laurent'],
    reviews: [],
  },
  {
    id: 'prod-winter-41',
    name: 'Robe Longue en Velours Valentino',
    slug: 'robe-longue-en-velours-valentino',
    price: 4500.00,
    description: 'Une robe du soir somptueuse en velours de soie, à la fois opulente et d\'une grande pureté de ligne.',
    category: 'womens-clothing',
    images: ['robe-longue-en-velours-valentino'],
    reviews: [],
  },
];


// --- Data-fetching functions ---

export function getProductsByCategory(categorySlug: string, limit?: number, excludeId?: string): Product[] {
  let filteredProducts: Product[];

  if (categorySlug === 'all') {
    filteredProducts = products;
  } else {
    filteredProducts = products.filter((p) => p.category === categorySlug);
  }

  if (excludeId) {
    filteredProducts = filteredProducts.filter((p) => p.id !== excludeId);
  }
  
  if (limit) {
    return filteredProducts.slice(0, limit);
  }

  return filteredProducts;
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getFeaturedProducts(limit: number = 4): Product[] {
    const winterProducts = products.filter(p => p.category === 'winter-clothing' || p.name.toLowerCase().includes('hiver') || p.name.toLowerCase().includes('manteau') || p.name.toLowerCase().includes('pull'));
    return winterProducts.slice(0, limit);
}
